apiVersion: v1
kind: Pod
metadata:
  name: init-test
spec:
  initContainers:
  - name: init-service
    image: busybox
    command:
    - sh
    - -c
    - "echo 'Initializing...'; sleep 10; echo 'Initialization completed' "

  containers:
  - name: init-mainservice
    image: busybox
    command:
    - sh
    - -c
    - "echo 'Main container started'"
