apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter-pod
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: jupyter/datascience-notebook:latest
        ports:
        - containerPort: 8888
        env:
        - name: JUPYTER_ENABLE_LAB
          value: "yes"
        args:
        - start-notebook.sh
        - "--NotebookApp.ip=0.0.0.0"
        - "--NotebookApp.port=8888"
        - "--NotebookApp.token=mytoken123"
